### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by jisantuc** [raster-foundry/raster-foundry-api-spec#1]
In CI, the spec should be run through the swagger validator, and if it passes and is a tagged commit, should push to the S3 location.

Requires:

- [x] a package.json with swagger validator
- [x] .travis.yml

**Comment by hectcastro** [comment]
This work relates to https://github.com/raster-foundry/raster-foundry-docs/issues/27 and requires undoing some work that was done in https://github.com/raster-foundry/raster-foundry/pull/1402.
